//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleWPF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int ID { get; set; }
        public int IDStudent { get; set; }
        public bool IsAbsent { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> TypePass { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual TypePass TypePass1 { get; set; }
    }
}
