//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleWPF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonSpezialization
    {
        public int IDLesson { get; set; }
        public string CodeSpecialization { get; set; }
        public int Course { get; set; }
        public int HoursFirstPart { get; set; }
        public int HoursSecondPart { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Specialization Specialization { get; set; }
    }
}
