//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleWPF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int IDGroup { get; set; }
        public int IDLesson { get; set; }
        public int IDClassroom { get; set; }
        public System.DateTime Date { get; set; }
        public byte Couple { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual Group Group { get; set; }
        public virtual Lesson Lesson { get; set; }
    }
}
