//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;

namespace ScheduleWPF.Entity
{
	using System;
	using System.Collections.Generic;

	public partial class Teacher
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public Teacher()
		{
			this.Groups = new HashSet<Group>();
			this.LessonTeachers = new HashSet<LessonTeacher>();
			this.Classrooms = new HashSet<Classroom>();
		}

		public int Code { get; set; }
		public string Surname { get; set; }
		public string Firstname { get; set; }
		public string Patronymic { get; set; }
		public string Fullname
		{
			get => $"{Surname} {Firstname} {Patronymic}";
		}
		public string Phone { get; set; }
		public string Email { get; set; }
		public Nullable<int> IDUser { get; set; }
		public string Address { get; set; }
		public string Group { get; set; }

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Group> Groups { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<LessonTeacher> LessonTeachers { get; set; }
		public virtual User User { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Classroom> Classrooms { get; set; }
	}
}
